if(ANDROID OR iOS)
	set(ENGINE_MOBILE_PLATFORM true)
elseif(CMAKE_SYSTEM_NAME STREQUAL Emscripten)
	set(ENGINE_WEB_PLATFORM true)
	set(CMAKE_EXECUTABLE_SUFFIX .html)
	add_link_options(-sUSE_WEBGL2=1 --shell-file=${CMAKE_CURRENT_SOURCE_DIR}/Platform/EmscriptenShell.html)
elseif (UNIX OR APPLE OR WIN32)
	set(ENGINE_DESKTOP_PLATFORM true)
else()
	message("Unable to detect platform to compile for")
endif()

if(ANDROID)
	include(${CMAKE_CURRENT_SOURCE_DIR}/Platform/Android/AppGlue.cmake)
endif()

# Graphics backends
if(ANDROID OR ENGINE_WEB_PLATFORM)
	set(GRAPHICS_BACKEND GLES3)
elseif(APPLE)
	set(GRAPHICS_BACKEND METAL)
elseif(WIN32)
	set(GRAPHICS_BACKEND D3D11)
else()
	set(GRAPHICS_BACKEND GLCORE)
endif()
add_definitions(-DSOKOL_${GRAPHICS_BACKEND})